### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Zer0nite** [Genom-Project/android_kernel_xiaomi_onc#4]
Installed all tools:
`apt-get install bc bash git-core gnupg build-essential zip curl make automake autogen autoconf autotools-dev libtool shtool python m4 gcc libtool zlib1g-dev flex`

Cloned miui kernel:
`git clone -b rebase-sdm-9-upstream https://github.com/rama982/android_kernel_xiaomi_onc.git onc`

buildkernel_local.sh copied to kernel dir and changed:
`DEVICE=onc-miui`
`CONFIG="onc-perf_defconfig"`

And run:
`chmod +x buildkernel_local.sh && ./buildkernel_local.sh 2>&1 | tee kernel.log`

Lots of warnings and errors:
[kernel.log](https://pastebin.com/evWjAdA8)

EDIT1:
I solved the problem, but i dont know how. But the wifi not working. I think missing wlan module.
`find -name *.ko`

`./AnyKernel3/modules/vendor/lib/modules/br_netfilter.ko`
`./AnyKernel3/modules/vendor/lib/modules/rdbg.ko`
`./AnyKernel3/modules/vendor/lib/modules/efivarfs.ko`
`./AnyKernel3/modules/vendor/lib/modules/mpq-adapter.ko`
`./AnyKernel3/modules/vendor/lib/modules/mpq-dmx-hw-plugin.ko`
`./AnyKernel3/modules/vendor/lib/modules/lcd.ko`
`./out/drivers/media/platform/msm/dvb/demux/mpq-dmx-hw-plugin.ko`
`./out/drivers/media/platform/msm/dvb/adapter/mpq-adapter.ko`
`./out/drivers/char/rdbg.ko`
`./out/drivers/video/backlight/lcd.ko`
`./out/fs/efivarfs/efivarfs.ko`
`./out/net/bridge/br_netfilter.ko`

EDIT2:
Everything is working now with @mylove90 build script. Thanks!

**Comment by Zer0nite** [comment]
I solved the problem, but i dont know how. But the wifi not working. I think missing wlan module.
`find -name *.ko`

`./AnyKernel3/modules/vendor/lib/modules/br_netfilter.ko`
`./AnyKernel3/modules/vendor/lib/modules/rdbg.ko`
`./AnyKernel3/modules/vendor/lib/modules/efivarfs.ko`
`./AnyKernel3/modules/vendor/lib/modules/mpq-adapter.ko`
`./AnyKernel3/modules/vendor/lib/modules/mpq-dmx-hw-plugin.ko`
`./AnyKernel3/modules/vendor/lib/modules/lcd.ko`
`./out/drivers/media/platform/msm/dvb/demux/mpq-dmx-hw-plugin.ko`
`./out/drivers/media/platform/msm/dvb/adapter/mpq-adapter.ko`
`./out/drivers/char/rdbg.ko`
`./out/drivers/video/backlight/lcd.ko`
`./out/fs/efivarfs/efivarfs.ko`
`./out/net/bridge/br_netfilter.ko`

**Comment by mylove90** [comment]
Just a couple of notes... Rama has retired don't disturb him again...
On my repo i got 2 branches stock & Q...those 2 branches are upstreamed stock kernels and got front cam working

**Comment by Zer0nite** [comment]
@mylove90 Oh.. okay just a last question. What is different between stock and pie branch?
And when I try your stock kernel sources the wlan module not created. But I'm trying to fix it.

**Comment by mylove90** [comment]
> @mylove90 Oh.. okay just a last question. What is different between stock and pie branch?
> And when I try your stock kernel sources the wlan module not created. But I'm trying to fix it.

Stock is just upstreamed stock kernel
Pie is my genom-magic source
Wlan is built inline in my stock branch to work with custom roms...read about kernel configuration to understand building kernel modules
